export const selectCharacter = [
	{
		options: [
			"Human",
			"Alien",
			"Humanoid",
			"unknown",
			"Poopybutthole",
			"Mythological Creature",
			"Animal",
			"Robot",
			"Cronenberg",
			"Disease",
		],
		title: "Species",
	},
	{
		options: ["Female", "Male", "Genderless", "unknown"],
		title: "Gender",
	},
	{
		options: ["Alive", "Dead", "unknown"],
		title: "Status",
	},
];
export const selectLocations = [
	{
		options: [
			"Planet",
			"Cluster",
			"Space station",
			"Microverse",
			"TV",
			"Resort",
			"Fantasy town",
			"Dream",
			"Dimension",
			"unknown",
			"Menagerie",
			"Game",
			"Customs",
			"Daycare",
			"Dwarf planet (Celestial Dwarf)",
			"Miniverse",
			"Teenyverse",
			"Box",
			"Spacecraft",
			"Artificially generated world",
			"Machine",
			"Arcade",
			"Spa",
			"Quadrant",
			"Quasar",
			"Mount",
			"Liquid",
			"Convention",
			"Woods",
			"Diegesis",
			"Non-Diegetic Alternative Reality",
			"Nightmare",
			"Asteroid",
			"Acid Plant",
			"Reality",
			"Death Star",
			"Base",
			"Elemental Rings",
			"Human",
			"Space",
			"Hell",
			"Police Department",
			"Country",
			"Consciousness",
			"Memory",
		],
		title: "Type",
	},
	{
		options: [
            "Dimension C-137",
            "unknown",
            "Post-Apocalyptic Dimension",
            "Replacement Dimension",
            "Cronenberg Dimension",
            "Fantasy Dimension",
            "Dimension 5-126",
            "Testicle Monster Dimension",
            "Cromulon Dimension",
            "Dimension C-500A",
            "Dimension K-83",
            "Dimension J19ζ7",
            "Eric Stoltz Mask Dimension",
            "Evil Rick's Target Dimension",
            "Giant Telepathic Spiders Dimension",
            "Unknown dimension",
            "Dimension K-22",
            "Dimension D-99",
            "Dimension D716",
            "Dimension D716-B",
            "Dimension D716-C",
            "Dimension J-22",
            "Dimension C-35",
            "Pizza Dimension",
            "Phone Dimension",
            "Chair Dimension",
            "Fascist Dimension",
            "Fascist Shrimp Dimension",
            "Fascist Teddy Bear Dimension",
            "Wasp Dimension",
            "Tusk Dimension",
            "Magic Dimension",
            "Merged Dimension",
        ],
		title: "Dimension",
	},
];




